# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apparel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apparel_type', models.CharField(max_length=255)),
                ('apparel_image', models.CharField(max_length=1000)),
                ('apparel_brand', models.CharField(max_length=255)),
                ('apparel_size', models.CharField(max_length=255)),
            ],
        ),
    ]
