# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apparel',
            old_name='apparel_brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='apparel',
            old_name='apparel_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='apparel',
            old_name='apparel_size',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='apparel',
            old_name='apparel_type',
            new_name='type',
        ),
    ]
