# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20171223_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='apparel',
            name='price',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
