# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_apparel_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApparelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='apparel',
            name='type',
        ),
        migrations.AddField(
            model_name='appareltype',
            name='apparel',
            field=models.ManyToManyField(to='shop.Apparel'),
        ),
    ]
