# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20171230_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appareltype',
            name='apparel',
        ),
        migrations.AddField(
            model_name='apparel',
            name='type',
            field=models.ManyToManyField(to='shop.ApparelType'),
        ),
    ]
