# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20171230_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='apparel',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apparel',
            name='image',
            field=models.FilePathField(path=None),
        ),
        migrations.AlterField(
            model_name='apparel',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='apparel',
            name='size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appareltype',
            name='image',
            field=models.FilePathField(),
        ),
    ]
