# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20180103_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apparel',
            name='type',
        ),
        migrations.AddField(
            model_name='apparel',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.ApparelType'),
            preserve_default=False,
        ),
    ]
