# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20180103_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apparel',
            name='size',
            field=models.CharField(max_length=255),
        ),
    ]
