# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20180103_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apparel',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
