# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title_image',
            new_name='article_image',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='article_title',
        ),
        migrations.AddField(
            model_name='article',
            name='article_content',
            field=models.CharField(default=1, max_length=6400),
            preserve_default=False,
        ),
    ]
