# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20171129_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_content',
            field=models.CharField(max_length=64),
        ),
    ]
